### ISSUE TITLE
The airplane doesn't land

### ISSUE THREAD

**Issue by MrSidou** [bogdan-todorovic/OpenGL_project#1]
Hi ... 
I have a question:::
I downloaded your project and ran it but the airplane doesn't land. Should I do something to land airplane or it itself will land???
Thank you

**Comment by t0db** [comment]
Hello MrSidou,

As I can remember, it should start an animation by pressing 'C' letter. If
it doesn't work, try other letters also.
Hope it works.

Best regards,

Bogdan Todorovic
